# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('profile_photo', models.ImageField(upload_to='pic/')),
                ('bio', models.CharField(max_length=30)),
                ('posted_projects', models.IntegerField()),
                ('contacts', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image_landing_page', models.ImageField(upload_to='picture/')),
                ('detailed_description', models.CharField(max_length=60)),
                ('link_to_livesite', models.CharField(max_length=30)),
            ],
        ),
    ]
