# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='posted_projects',
            new_name='posted_project',
        ),
    ]
