# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0003_auto_20190401_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posted_projects',
        ),
    ]
