# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0004_remove_profile_posted_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='link_to_livesite',
        ),
    ]
