# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0005_remove_projects_link_to_livesite'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link_to_livesite',
            field=models.CharField(default=6, max_length=30),
            preserve_default=False,
        ),
    ]
