# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0007_wingsdmerch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wingsdMerch',
        ),
    ]
