# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0010_profile_posted_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='posted_projects',
        ),
    ]
