# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0011_remove_profile_posted_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default=6, upload_to='pic/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_landing_page',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='picture/'),
            preserve_default=False,
        ),
    ]
