# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0012_auto_20190404_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='pic/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image_landing_page',
            field=models.ImageField(null=True, upload_to='picture/'),
        ),
    ]
