# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0018_auto_20190404_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.CharField(default=5, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='content',
        ),
    ]
